import { X } from 'lucide-react';

export default function ProfileEditor({ form, setForm, isSaving, isUploading, onClose, onSave, onUpload }) {
  const updateField = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const handleUpload = (type) => (event) => {
    const [file] = event.target.files;
    if (file) onUpload(file, type);
  };
  return <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-900/30 p-4 backdrop-blur-sm"><form onSubmit={onSave} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Editar perfil</h2><button type="button" onClick={onClose} className="rounded-full p-2 text-slate-500 hover:bg-slate-100" aria-label="Fechar"><X className="h-5 w-5" /></button></div><div className="mt-6 space-y-4"><label className="block text-sm font-semibold text-slate-700">Nome<input value={form.name} onChange={updateField('name')} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-indigo-500" required /></label><label className="block text-sm font-semibold text-slate-700">Nome de usuário<input value={form.handle} onChange={updateField('handle')} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-indigo-500" placeholder="whitecloud" /></label><label className="block text-sm font-semibold text-slate-700">Bio<textarea value={form.bio} onChange={updateField('bio')} maxLength={160} className="mt-2 min-h-24 w-full resize-none rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-indigo-500" placeholder="Conte algo sobre você" /></label><div className="grid grid-cols-2 gap-3"><label className="cursor-pointer rounded-lg border border-dashed border-slate-300 p-3 text-center text-xs font-semibold text-slate-600 hover:border-indigo-400"><span>Foto de perfil</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleUpload('avatar')} className="sr-only" disabled={isUploading} /></label><label className="cursor-pointer rounded-lg border border-dashed border-slate-300 p-3 text-center text-xs font-semibold text-slate-600 hover:border-indigo-400"><span>Imagem de capa</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleUpload('cover')} className="sr-only" disabled={isUploading} /></label></div><p className="text-xs text-slate-400">Use imagens de até 5 MB. {isUploading ? 'Enviando...' : ''}</p></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Cancelar</button><button type="submit" disabled={isSaving || isUploading} className="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-semibold text-white hover:bg-indigo-700 disabled:bg-indigo-300">{isSaving ? 'Salvando...' : 'Salvar perfil'}</button></div></form></div>;
}